#include "CryIf_Cfg.h"

 CRYIF_CHANNEL  CHANNELS [NO_OF_CHANNELS]=
 { 
{ CRYIF_CHANNEL_A_ID ,  CRYPTO_DRIVER_OBJECT_A   },
{ CRYIF_CHANNEL_B_ID ,  CRYPTO_DRIVER_OBJECT_B   },
{ CRYIF_CHANNEL_C_ID ,   CRYPTO_DRIVER_OBJECT_C  }
 
 };


CRYIF_KEY KEYS [NO_OF_KEYS]=
 {

{ CRYIF_KEY_ID_A,  CryptoKey_A   },
{  CRYIF_KEY_ID_B ,CryptoKey_B   },
{  CRYIF_KEY_ID_C, CryptoKey_C   }

};
 
	

